import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoadingWrapper from "@/components/LoadingWrapper";
import ConditionalLayout from "./ConditonalLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <ConditionalLayout>
          <LoadingWrapper>{children}</LoadingWrapper>
        </ConditionalLayout>
      </body>
    </html>
  );
}
