import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoadingWrapper from "@/components/LoadingWrapper";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        <header className="bg-gradient-to-r from-gray-900 to-gray-700 p-4">
          <Navbar />
        </header>
        <main className="flex-grow z-20 bg-white">
          <LoadingWrapper>{children}</LoadingWrapper>
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
